// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token     string `json:"token"`
	User      *User  `json:"user"`
	ExpiresAt string `json:"expiresAt"`
}

type Comment struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Author    *User  `json:"author"`
	Post      *Post  `json:"post"`
	CreatedAt string `json:"createdAt"`
}

type CreatePostInput struct {
	Title     string   `json:"title"`
	Content   string   `json:"content"`
	Tags      []string `json:"tags"`
	Published *bool    `json:"published,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PaginationInput struct {
	Page  *int32 `json:"page,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

type Post struct {
	ID        string   `json:"id"`
	Title     string   `json:"title"`
	Content   string   `json:"content"`
	Author    *User    `json:"author"`
	Tags      []string `json:"tags"`
	Published bool     `json:"published"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type PostConnection struct {
	Edges      []*PostEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int32       `json:"totalCount"`
}

type PostEdge struct {
	Node   *Post  `json:"node"`
	Cursor string `json:"cursor"`
}

type PostFilters struct {
	AuthorID   *string  `json:"authorId,omitempty"`
	Published  *bool    `json:"published,omitempty"`
	Tags       []string `json:"tags,omitempty"`
	SearchTerm *string  `json:"searchTerm,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type UpdatePostInput struct {
	Title     *string  `json:"title,omitempty"`
	Content   *string  `json:"content,omitempty"`
	Tags      []string `json:"tags,omitempty"`
	Published *bool    `json:"published,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	Avatar    *string `json:"avatar,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}
